//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int IdMovimiento { get; set; }
        public int IdCuenta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<decimal> ValorRetiro { get; set; }
        public Nullable<decimal> ValorGmf { get; set; }
        public Nullable<decimal> SaldoMov { get; set; }
        public string CuentaDestino { get; set; }
        public string TipoTransaccion { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
    }
}
